# SPDX-FileCopyrightText: 2006-2025 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2025 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC-BY-4.0

name: 'Update CPM Package Lock'
description: 'Updates packages in a CPM package-lock file'
inputs:
  package_lock_file:
    description: "Path to CPM's package lock file."
    required: true
  ignored_packages:
    description: "List of packages to ignore."
    required: false
  token:
    description: "Personal Access Token (PAT)."
    required: true
  gpg_key:
    description: "Private GPG key for signing commits."
    required: false
  gpg_passphrase:
    description: "Passphrase for GPG key."
    required: false
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}
        path: repo

    - name: Update CPM Package Lock
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        mkdir -p build && cd build
        cmake ${GITHUB_ACTION_PATH} \
          -DPACKAGE_LOCK="${GITHUB_WORKSPACE}/repo/${{ inputs.package_lock_file }}" \
          "-DIGNORED_PACKAGES=${{ inputs.ignored_packages }}"

    - name: Update CPM
      id: update_cpm
      shell: bash
      working-directory: repo
      run: |
        CPM_FILE=$(find . -type f -name "CPM.cmake")
        if [[ -n "${CPM_FILE}" ]]; then
          wget --quiet --retry-connrefused --output-document "${CPM_FILE}" https://github.com/cpm-cmake/CPM.cmake/releases/latest/download/get_cpm.cmake
          echo "cpm_file=${CPM_FILE}" >> "${GITHUB_OUTPUT}"
        fi
        CMAKE_FORMAT_FILE=$(find . -type f -name ".cmake-format.yaml")
        if [[ -n "${CMAKE_FORMAT_FILE}" ]]; then
          echo "cmake_format_file=${CMAKE_FORMAT_FILE}" >> "${GITHUB_OUTPUT}"
        fi

    - name: Run cmake-format
      continue-on-error: true
      if: steps.update_cpm.outputs.cpm_file && steps.update_cpm.outputs.cmake_format_file
      shell: bash
      working-directory: repo
      run : |
        SUDO=$(command -v sudo &> /dev/null && echo 'sudo' || echo '')
        ${SUDO} apt-get update &> /dev/null
        ${SUDO} apt-get install --yes cmake-format &> /dev/null
        cmake-format --version
        cmake-format --config-files ${{ steps.update_cpm.outputs.cmake_format_file }} --in-place ${{ steps.update_cpm.outputs.cpm_file}}

    - name: Import GPG key
      if: inputs.gpg_key != '' && inputs.gpg_passphrase != ''
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        workdir: repo
        gpg_private_key: ${{ inputs.gpg_key }}
        passphrase: ${{ inputs.gpg_passphrase }}
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: Open PR
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.token }}
        commit-message: "[INFRA] Update CPM Packages"
        committer: "seqan-actions[bot] <seqan-actions@users.noreply.github.com>"
        author: "seqan-actions[bot] <seqan-actions@users.noreply.github.com>"
        branch: "actions/update_cpm_package_lock"
        delete-branch: true
        title: "[INFRA] Update CPM Packages"
        body: ""
        path: repo
        add-paths: |
          ${{ inputs.package_lock_file }}
          ${{ steps.update_cpm.outputs.cpm_file}}
