name: 'Setup Package Manager'
description: 'Configures apt (Linux) and brew (macOS)'
runs:
  using: 'composite'
  steps:
  - name: Configure APT
    if: runner.os == 'Linux' && env.SEQAN_ACTIONS_SETUP_PACKAGE_MANAGER_RAN != 'true'
    shell: bash
    run: ${{ github.action_path }}/configure_apt.sh

  - name: Configure Homebrew
    if: runner.os == 'macOS' && env.SEQAN_ACTIONS_SETUP_PACKAGE_MANAGER_RAN != 'true'
    uses: Homebrew/actions/setup-homebrew@master

  - name: Export install script
    if: env.SEQAN_ACTIONS_SETUP_PACKAGE_MANAGER_RAN != 'true'
    shell: bash
    run: |
      SCRIPT_DIR=/tmp/seqan_actions_setup_package_manager
      mkdir -p ${SCRIPT_DIR}
      cp ${{ github.action_path }}/install ${SCRIPT_DIR}
      echo "${SCRIPT_DIR}" >> $GITHUB_PATH

  - name: Export environment variable
    if: env.SEQAN_ACTIONS_SETUP_PACKAGE_MANAGER_RAN != 'true'
    shell: bash
    run: echo "SEQAN_ACTIONS_SETUP_PACKAGE_MANAGER_RAN=true" >> "$GITHUB_ENV"

