# SPDX-FileCopyrightText: 2006-2024 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2024 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC-BY-4.0

name: 'Setup Package Manager'
description: 'Configures apt (Linux) and brew (macOS)'
runs:
  using: 'composite'
  steps:
  - name: Configure APT
    if: runner.os == 'Linux' && env.SEQAN_ACTIONS_SETUP_PACKAGE_MANAGER_RAN != 'true'
    shell: bash
    run: ${GITHUB_ACTION_PATH}/configure_apt.sh

  - name: Setup Homebrew
    if: runner.os == 'macOS' && env.SEQAN_ACTIONS_SETUP_PACKAGE_MANAGER_RAN != 'true'
    uses: Homebrew/actions/setup-homebrew@master

  - name: Configure Homebrew
    if: runner.os == 'macOS' && env.SEQAN_ACTIONS_SETUP_PACKAGE_MANAGER_RAN != 'true'
    shell: bash
    run: brew analytics on

  - name: Export install script
    if: env.SEQAN_ACTIONS_SETUP_PACKAGE_MANAGER_RAN != 'true'
    shell: bash
    run: |
      SCRIPT_DIR=/tmp/seqan_actions_setup_package_manager
      mkdir -p ${SCRIPT_DIR}
      cp ${GITHUB_ACTION_PATH}/install ${SCRIPT_DIR}
      echo "${SCRIPT_DIR}" >> $GITHUB_PATH

  - name: Export environment variable
    if: env.SEQAN_ACTIONS_SETUP_PACKAGE_MANAGER_RAN != 'true'
    shell: bash
    run: echo "SEQAN_ACTIONS_SETUP_PACKAGE_MANAGER_RAN=true" >> "$GITHUB_ENV"
