# SPDX-FileCopyrightText: 2006-2025 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2025 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC-BY-4.0

name: 'Setup CI tools'
description: 'Installs a compiler, ccache, and actions/cache'
inputs:
  compiler:
    description: "Compiler to install, e.g., gcc-13 or clang-17 or intel-2023.2.1"
    required: true
  ccache_size:
    description: "The ccache maximum size."
    required: false
    default: 75M
runs:
  using: 'composite'
  steps:
  - name: Install compiler
    uses: seqan/actions/setup-compiler@main
    with:
      compiler: ${{ inputs.compiler }}

  - name: Install ccache and setup actions/cache
    uses: seqan/actions/setup-cache@main
    with:
      ccache_size: ${{ inputs.ccache_size }}

