name: 'Setup CI tools'
description: 'Installs dependencies for SeqAn CI'
inputs:
  compiler:
    description: "Compiler to install, e.g., gcc-12 or clang-15."
    required: true
  ccache_size:
    description: "The ccache maximum size."
    required: false
    default: 75M
  use_actions_cache:
    description: "Configure actions/cache for ccache. true or false."
    required: false
    default: true
runs:
  using: 'composite'
  steps:
  - name: Setup Package Manager
    uses: seqan/actions/setup-package-manager@main

  - name: Install ccache
    shell: bash
    run: install ccache

  - name: Install compiler ${{ inputs.compiler }}
    shell: bash
    run: |
      install ${{ inputs.compiler }}
      echo "CC=${{ inputs.compiler }}" >> "$GITHUB_ENV"
      echo "CXX=$(echo ${{ inputs.compiler }} | sed 's/gcc/g++/' | sed 's/clang/clang++/')" >> "$GITHUB_ENV"

  - name: Export ccache config
    shell: bash
    run: |
      echo "CCACHE_BASEDIR=${{ github.workspace }}" >> "$GITHUB_ENV"
      echo "CCACHE_DIR=${{ github.workspace }}/.ccache" >> "$GITHUB_ENV"
      echo "CCACHE_COMPRESS=true" >> "$GITHUB_ENV"
      echo "CCACHE_COMPRESSLEVEL=12" >> "$GITHUB_ENV"
      echo "CCACHE_MAXSIZE=${{ inputs.ccache_size }}" >> "$GITHUB_ENV"

  - name: Export other configs
    shell: bash
    run: |
      echo "GNUMAKEFLAGS=--no-print-directory" >> "$GITHUB_ENV"

  - name: Load ccache
    if: inputs.use_actions_cache == 'true'
    uses: actions/cache@v3
    with:
      path: ${{ env.CCACHE_DIR }}
      key: ccache-${{ runner.os }}-${{ github.workflow }}-${{ matrix.name }}-${{ github.ref }}
      # Restoring: From current branch, otherwise from base branch, otherwise from any branch.
      restore-keys: |
        ccache-${{ runner.os }}-${{ github.workflow }}-${{ matrix.name }}-${{ github.ref }}
        ccache-${{ runner.os }}-${{ github.workflow }}-${{ matrix.name }}-${{ github.base_ref }}
        ccache-${{ runner.os }}-${{ github.workflow }}-${{ matrix.name }}
