# SPDX-FileCopyrightText: 2006-2025 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2025 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC-BY-4.0

name: 'Setup Doxygen'
description: 'Installs Doxygen'
inputs:
  doxygen:
    description: "Doxygen version to install, e.g., 1.9.6."
    required: true
runs:
  using: 'composite'
  steps:
  - name: Install Doxygen
    shell: bash
    run: ${GITHUB_ACTION_PATH}/install_doxygen.sh ${{ inputs.doxygen }}
