# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/lint"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/setup-cache"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/setup-cmake"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/setup-compiler"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/setup-doxygen"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/setup-package-manager"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/setup-toolchain"
    schedule:
      interval: "weekly"
