# SPDX-FileCopyrightText: 2006-2025 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2025 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC-BY-4.0

services:
  gcc-11:
    image: ghcr.io/seqan/gcc-11
    pull_policy: never
    build:
      args:
        GCC_VERSION: 11

  gcc-12:
    image: ghcr.io/seqan/gcc-12
    pull_policy: never
    build:
      args:
        GCC_VERSION: 12

  gcc-13:
    image: ghcr.io/seqan/gcc-13
    pull_policy: never
    build:
      args:
        GCC_VERSION: 13
      tags:
        - ghcr.io/seqan/gcc-third-latest

  gcc-14:
    image: ghcr.io/seqan/gcc-14
    pull_policy: never
    build:
      args:
        GCC_VERSION: 14
      tags:
        - ghcr.io/seqan/gcc-second-latest

  gcc-15:
    image: ghcr.io/seqan/gcc-15
    pull_policy: never
    build:
      args:
        GCC_VERSION: 15
      tags:
        - ghcr.io/seqan/gcc-latest
