# SPDX-FileCopyrightText: 2006-2024 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2024 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC-BY-4.0

name: 'Setup CMake'
description: 'Installs CMake'
inputs:
  cmake:
    description: "CMake version to install, e.g., 3.16.9."
    required: true
runs:
  using: 'composite'
  steps:
  - name: Install CMake
    shell: bash
    run: ${{ github.action_path }}/install_cmake.sh ${{ inputs.cmake }}
