# SPDX-FileCopyrightText: 2006-2025 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2025 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC-BY-4.0

name: 'Setup Cache'
description: 'Installs ccache and actions/cache'
inputs:
  ccache_size:
    description: "The ccache maximum size."
    required: false
    default: 75M
runs:
  using: 'composite'
  steps:
  - name: Setup Package Manager
    uses: seqan/actions/setup-package-manager@main

  - name: Install ccache
    shell: bash
    run: install ccache

  - name: Export ccache config
    shell: bash
    run: |
      echo "CCACHE_BASEDIR=${{ github.workspace }}" >> "$GITHUB_ENV"
      echo "CCACHE_DIR=${{ github.workspace }}/.ccache" >> "$GITHUB_ENV"
      echo "CCACHE_COMPRESS=true" >> "$GITHUB_ENV"
      echo "CCACHE_COMPRESSLEVEL=12" >> "$GITHUB_ENV"
      echo "CCACHE_MAXSIZE=${{ inputs.ccache_size }}" >> "$GITHUB_ENV"
      echo "CCACHE_IGNOREOPTIONS=-fprofile-abs-path" >> "$GITHUB_ENV"

  - name: Setup Cache
    uses: seqan/actions/setup-actions-cache@main
