name: 'Setup Compiler'
description: 'Installs a compiler'
inputs:
  compiler:
    description: "Compiler to install, e.g., gcc-13 or clang-17 or intel-2023.2.1 (intel for latest)"
    required: true
runs:
  using: 'composite'
  steps:
  - name: Setup Package Manager
    uses: seqan/actions/setup-package-manager@main

  - name: Install GCC
    if: contains(inputs.compiler, 'gcc')
    shell: bash
    run: |
      install ${{ inputs.compiler }}
      echo "CC=${{ inputs.compiler }}" >> "$GITHUB_ENV"
      echo "CXX=$(echo ${{ inputs.compiler }} | sed 's/gcc/g++/' | sed 's/clang/clang++/')" >> "$GITHUB_ENV"

  - name: Install Clang
    if: contains(inputs.compiler, 'clang')
    shell: bash
    run: |
      install ${{ inputs.compiler }}
      echo "CC=${{ inputs.compiler }}" >> "$GITHUB_ENV"
      echo "CXX=$(echo ${{ inputs.compiler }} | sed 's/clang/clang++/')" >> "$GITHUB_ENV"
      if [ "${RUNNER_OS}" == "Linux" ]; then
        CLANG=${{ inputs.compiler }}
        CLANG_VERSION=${CLANG:6}
        install lld-${CLANG_VERSION} libc++-${CLANG_VERSION}-dev libc++abi-${CLANG_VERSION}-dev libomp-${CLANG_VERSION}-dev
        echo "OMP_TOOL_LIBRARIES=/usr/lib/llvm-${CLANG_VERSION}/lib/libarcher.so" >> "$GITHUB_ENV"
        sudo ln -fs /usr/bin/llvm-as-${CLANG_VERSION} /usr/bin/as
        sudo ln -fs /usr/bin/llvm-ar-${CLANG_VERSION} /usr/bin/ar
        sudo ln -fs /usr/bin/ld.lld-${CLANG_VERSION} /usr/bin/ld
        sudo ln -fs /usr/bin/llvm-nm-${CLANG_VERSION} /usr/bin/nm
        sudo ln -fs /usr/bin/llvm-ranlib-${CLANG_VERSION} /usr/bin/ranlib
        if [[ ! -e "/usr/lib/llvm-${CLANG_VERSION}/lib/libclang-${CLANG_VERSION}.so.1" ]]; then
          sudo ln -fs /usr/lib/llvm-${CLANG_VERSION}/lib/libclang-${CLANG_VERSION}.so.1 /usr/lib/llvm-${CLANG_VERSION}/lib/libclang-${CLANG_VERSION}.so.${CLANG_VERSION}
        fi
      fi
      if [ "${RUNNER_OS}" == "macOS" ]; then
        CLANG=${{ inputs.compiler }}
        CLANG_VERSION=${CLANG:6}
        INSTALL_PREFIX=$(brew --prefix llvm@${CLANG_VERSION})
        echo "LDFLAGS=-L${INSTALL_PREFIX}/lib/c++ -Wl,-rpath,${INSTALL_PREFIX}/lib/c++" >> "$GITHUB_ENV"
        sudo ln -fs ${INSTALL_PREFIX}/bin/clang++ ${INSTALL_PREFIX}/bin/clang++-${CLANG_VERSION}
        sudo ln -fs ${INSTALL_PREFIX}/bin/llvm-ar ${INSTALL_PREFIX}/bin/ar
        sudo ln -fs ${INSTALL_PREFIX}/bin/llvm-as ${INSTALL_PREFIX}/bin/as
        sudo ln -fs ${INSTALL_PREFIX}/bin/llvm-nm ${INSTALL_PREFIX}/bin/nm
        sudo ln -fs ${INSTALL_PREFIX}/bin/llvm-ranlib ${INSTALL_PREFIX}/bin/ranlib
        echo "${INSTALL_PREFIX}/bin" >> "${GITHUB_PATH}"
      fi

  - name: Install Intel
    if: contains(inputs.compiler, 'intel')
    shell: bash
    run: |
      install $(echo ${{ inputs.compiler }} | sed 's/intel/intel-oneapi-compiler-dpcpp-cpp/')
      source /opt/intel/oneapi/setvars.sh
      sudo ln -fs $(icpx --print-prog-name=llvm-ar) /usr/bin/ar
      sudo ln -fs $(icpx --print-prog-name=lld) /usr/bin/ld
      sudo ln -fs $(icpx --print-prog-name=llvm-nm) /usr/bin/nm
      sudo ln -fs $(icpx --print-prog-name=llvm-ranlib) /usr/bin/ranlib
      echo "CC=icx" >> "${GITHUB_ENV}"
      echo "CXX=icpx" >> "${GITHUB_ENV}"
      echo "${PATH}" > "${GITHUB_PATH}"
      echo "TBBROOT=${TBBROOT}" >> "${GITHUB_ENV}"
      echo "ONEAPI_ROOT=${ONEAPI_ROOT}" >> "${GITHUB_ENV}"
      echo "PKG_CONFIG_PATH=${PKG_CONFIG_PATH}" >> "${GITHUB_ENV}"
      echo "ACL_BOARD_VENDOR_PATH=${ACL_BOARD_VENDOR_PATH}" >> "${GITHUB_ENV}"
      echo "FPGA_VARS_DIR=${FPGA_VARS_DIR}" >> "${GITHUB_ENV}"
      echo "DIAGUTIL_PATH=${DIAGUTIL_PATH}" >> "${GITHUB_ENV}"
      echo "DPL_ROOT=${DPL_ROOT}" >> "${GITHUB_ENV}"
      echo "MANPATH=${MANPATH}" >> "${GITHUB_ENV}"
      echo "GDB_INFO=${GDB_INFO}" >> "${GITHUB_ENV}"
      echo "SETVARS_COMPLETED=${SETVARS_COMPLETED}" >> "${GITHUB_ENV}"
      echo "CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}" >> "${GITHUB_ENV}"
      echo "CMPLR_ROOT=${CMPLR_ROOT}" >> "${GITHUB_ENV}"
      echo "FPGA_VARS_ARGS=${FPGA_VARS_ARGS}" >> "${GITHUB_ENV}"
      echo "INFOPATH=${INFOPATH}" >> "${GITHUB_ENV}"
      echo "LIBRARY_PATH=${LIBRARY_PATH}" >> "${GITHUB_ENV}"
      echo "OCL_ICD_FILENAMES=${OCL_ICD_FILENAMES}" >> "${GITHUB_ENV}"
      echo "INTELFPGAOCLSDKROOT=${INTELFPGAOCLSDKROOT}" >> "${GITHUB_ENV}"
      echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}" >> "${GITHUB_ENV}"
      echo "NLSPATH=${NLSPATH}" >> "${GITHUB_ENV}"
      echo "INTEL_PYTHONHOME=${INTEL_PYTHONHOME}" >> "${GITHUB_ENV}"
      echo "CPATH=${CPATH}" >> "${GITHUB_ENV}"

  - name: Export configs
    shell: bash
    run: |
      echo "GNUMAKEFLAGS=--no-print-directory --output-sync=target" >> "$GITHUB_ENV"
