# SPDX-FileCopyrightText: 2006-2025 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2025 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC-BY-4.0

services:
  iwyu:
    image: ghcr.io/seqan/iwyu
    pull_policy: never
    build:
      args:
        CLANG_VERSION: 20
        IWYU_VERSION: 0.24
