# SPDX-FileCopyrightText: 2006-2024 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2024 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC-BY-4.0

name: Delete Old Containers

on:
  workflow_run:
    workflows:
      - Build Containers
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: delete
  cancel-in-progress: false

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eexuo pipefail {0}

jobs:
  get_container_names:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
    outputs:
      container_names: ${{ steps.get_container_names.outputs.container_names }}
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Get container names
        id: get_container_names
        # https://github.com/cli/cli/issues/9606#issuecomment-2433338481
        env:
          GH_TOKEN: ${{ secrets.SEQAN_ACTIONS_PAT }}
        run: |
          container_names=$(gh api -XGET /orgs/seqan/packages -F package_type=container | jq '.[].name' | jq --slurp --compact-output)
          echo "container_names=${container_names}" >> $GITHUB_OUTPUT

  delete_old_containers:
    needs: get_container_names
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.get_container_names.outputs.container_names) }}
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Delete old containers
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ matrix.package }}
          package-type: container
          min-versions-to-keep: 1
          delete-only-untagged-versions: true

